# yaml 配置
version: "3.3"
services:
  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    restart: always
    container_name: mysql
    volumes:
      - ./init.sql:/data/application/init.sql
      - ./mysql:/var/lib/mysql
    command: "--default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql"
  wenku:
    build: .
    container_name: wenku
    depends_on:
      - mysql
    volumes:
      - ./config.json:/config.json
    ports:
    - 80:9898